app/urls.py
from django.urls import path, include

from . import views

app_name = "app"

urlpatterns = [
    path("settings/", views.settings_view, name="settings_view"),
    path("paciente/", include("paciente.urls")),
]

medical_tools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path("auth/", include('auth_app.urls')),
    path("app/", include('app.urls')),
]

paciente/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.paciente_view, name="paciente_view"),
    path("<int:paciente_id>", views.paciente_file, name="paciente_file"),
    path("new/", views.paciente_new, name="paciente_new"),
    path("api/new/", views.paciente, name="paciente"),
]

paciente/models.py
from django.db import models


import uuid
# Create your models here.
class Paciente(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    comentario = models.CharField(max_length=400, default='n/a')
    nombre = models.CharField(max_length=50, null=False, default='n/a')
    apellidos = models.CharField(max_length=100, default='n/a')
    fecha_nacimiento = models.CharField(max_length=100, default='n/a')
    tipo_documento = models.CharField(max_length=100, default='n/a')
    documento_identidad = models.CharField(max_length=100, default='n/a')
    sexo = models.CharField(max_length=100, default='n/a')
    telefono = models.CharField(max_length=100, default='n/a')
    telefono_adicional = models.CharField(max_length=100, default='n/a')
    email = models.CharField(max_length=100, default='n/a')
    
    calle = models.CharField(max_length=100, default='n/a')
    numero = models.CharField(max_length=100, default='n/a')
    puerta = models.CharField(max_length=100, default='n/a')
    pais = models.CharField(max_length=100, default='n/a')
    ciudad = models.CharField(max_length=100, default='n/a')
    cp = models.CharField(max_length=100, default='n/a')
    
    aseguradora = models.CharField(max_length=100, default='n/a')
    numero_seguro = models.CharField(max_length=100, default='n/a')
    otros_datos = models.TextField(default='n/a')
    
    fecha_registro = models.DateField(auto_now_add=True)
    photo = models.URLField(max_length=200, default="https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png")
    LPD = models.URLField(max_length=200, default='n/a')
    
    
    
class Historial(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    
    
class Episodio(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    historial = models.ForeignKey(Historial, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    diagnostico = models.TextField()
    alergias = models.TextField()
    seguimiento = models.TextField()
    recomendacion = models.TextField()
    
    
class Receta(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    episodio = models.ForeignKey(Episodio, on_delete=models.CASCADE)
    medicamento = models.CharField(max_length=50)
    dosis = models.CharField(max_length=50)
    frecuencia = models.CharField(max_length=50)
    duracion = models.CharField(max_length=50)
    observaciones = models.TextField()

paciente/views.py
from django.shortcuts import render

from .models import Paciente


# Create your views here.
def paciente_view(request):
    return render(request, "app/paciente/paciente_view.html")

def paciente_file(request, paciente_id):
    if request.method == "POST":
        paciente = Paciente.objects.filter(id=paciente_id).first()
    return render(request, "app/paciente/paciente_file.html", {"paciente": paciente})

def paciente_new(request):
    return render(request, "app/paciente/paciente_new.html")


def paciente(request):
    if request.method == "POST":
        paciente = Paciente()
        paciente.nombre = request.POST.get("nombre")
        paciente.apellidos = request.POST.get("apellidos")
        paciente.fecha_nacimiento = request.POST.get("fecha_nacimiento")
        paciente.tipo_documento = request.POST.get("tipo_documento")
        paciente.documento_identidad = request.POST.get("documento_identidad")
        paciente.tipo_documento = request.POST.get("tipo_documento")
        paciente.sexo = request.POST.get("sexo")
        paciente.telefono = request.POST.get("telefono")
        paciente.telefono_adicional = request.POST.get("telefono_adicional")
        paciente.email = request.POST.get("email")
        paciente.calle = request.POST.get("calle")
        paciente.numero = request.POST.get("numero")
        paciente.puerta = request.POST.get("puerta")
        paciente.pais = request.POST.get("pais")
        paciente.ciudad = request.POST.get("ciudad")
        paciente.cp = request.POST.get("cp")
        paciente.aseguradora = request.POST.get("aseguradora")
        paciente.numero_seguro = request.POST.get("numero_seguro")
        paciente.otros_datos = request.POST.get("otros_datos")
        paciente.save()
        if paciente:
            print("Paciente creado")
            return render(request, "app/paciente/paciente_file.html", {"paciente": paciente})
        else:
            print("Error al crear el paciente")
            return render(request, "app/paciente/paciente_new.html")

templates/app/paciente/components/buscador_paciente_view.html
<div class="row w-100">
    <!--Buscador de usuario-->
    <div class="col-3 ms-4 mt-2">
        <div class="input-group mb-2 ">
            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-magnifying-glass col-2"></i></span>
            <input type="text" class="form-control" placeholder="Busqueda por nombre, apellido, telf..." aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <span class="row text-center ms-3"> Se han encontrado 187 resultados</span>
    </div>

    <!--Boton de agregar usuario-->
    <div class="col-3 mt-2">
        <select class="form-select form-select " aria-label="Large select example">
            <option selected>Datos de Contacto</option>
            <option value="1">Telefono</option>
            <option value="2">Email</option>
        </select>
    </div>

    <!--Boton de agregar usuario-->
    <div class="col-3 mt-2">
        <select class="form-select form-select " aria-label="Large select example">
            <option selected>Ordenar por</option>
            <option value="1">Telefono</option>
            <option value="2">Email</option>
        </select>
    </div>


</div>

templates/app/paciente/components/menu_paciente_view.html
<header class="row w-100 d-flex justify-content-between p-3 align-items-center border-bottom">
    <h1 class="col fs-3 ms-2">Pacientes</h1>
    
    <div class="col-2 p-0 d-flex justify-content-end">
        <a class="btn btn-info w-75" href="{% url 'app:paciente_new' %}">
            + Añadir Paciente
        </a>
    </div>
</header>