app/urls.py
from django.urls import path, include

from . import views

app_name = "app"

urlpatterns = [
    path("settings/", views.settings_view, name="settings_view"),
    path("paciente/", include("paciente.urls")),
]

medical_tools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path("auth/", include('auth_app.urls')),
    path("app/", include('app.urls')),
]

paciente/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.paciente_view, name="paciente_view"),
    path("<int:paciente_id>", views.paciente_file, name="paciente_file"),
    path("new/", views.paciente_new, name="paciente_new"),
    path("api/new/", views.paciente, name="paciente"),
]

templates/app/base_app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}
        
    {% endblock title %}

    
    {% block libs %}
        
    {% endblock libs %}
        

    <!-- # Bootstrap CDN -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <!-- # Font Awesome CDN -->
    <script src="https://kit.fontawesome.com/ee37c672c1.js" crossorigin="anonymous"></script>
    

    <!--Custom Styles-->
    <link rel="stylesheet" href="{% static 'css/base_app.css' %}">

</head>
<body class="overflow-x-hidden">
    <section class="container-fluid ">
        <section class="row-12 text-secondary d-flex border-end">
            <nav class="menu d-flex flex-column d-flex flex-column justify-content-between">
                
                <ul class="nav d-flex flex-column p-2 fs-4 align-items-center gap-2">
                    <!--Icon-->
                    <li><i class="fa-solid fa-star-of-life text-info fs-2"></i></li>
                    <!--Icon-->
                    <!--Calendar-->
                    <li><a href=""><i class="fa-regular fa-calendar mt-5 text-secondary icon_menu"></i></a></li>
                    <!--Paciente-->
                    <li><a href="{% url 'app:paciente_view' %}"><i class="fa-solid fa-user-group text-secondary icon_menu"></i></a></li>
                    <!--chat-->
                    <li><a href=""><i class="fa-solid fa-comment-dots text-secondary icon_menu"></i></a></li>
                    <!--Estadistica-->
                    <li><a href=""><i class="fa-solid fa-chart-column text-secondary icon_menu"></i></a></li>
                    <!--Email-->
                    <li><a href=""><i class="fa-regular fa-paper-plane text-secondary icon_menu"></i></a></li>
                    <!--Configuracion-->
                    <li><a href=""><i class="fa-solid fa-gear text-secondary icon_menu"></i></a></li>
                </ul>

                <ul class="nav d-flex flex-column fs-3 align-items-center gap-2">
                    <li><a href=""><i class="fa-regular fa-circle-question text-secondary icon_menu"></i></a></li>
                    <li><a href=""><i class="fa-regular fa-bell text-secondary icon_menu"></i></a></li>    
                    <li><a href=""><i class="fa-regular fa-circle-user text-secondary icon_menu"></i></a></li>
                </ul>
                    
            </nav>

            <section class="col content_app">
                {% block content_app %}
                    
                {% endblock content_app %}
            </section>       
        </section>
    </section>
</body>
</html>

templates/app/settings.html
{% extends 'app/base_app.html' %}
{% block title %}
    <title>Settings</title>
{% endblock title %}


{% block content_app %}
    <h1>Home</h1>
{% endblock content_app %}
```