app/urls.py
from django.urls import path, include

from . import views

app_name = "app"

urlpatterns = [
    path("settings/", views.settings_view, name="settings_view"),
    path("paciente/", include("paciente.urls")),
]

medical_tools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path("auth/", include('auth_app.urls')),
    path("app/", include('app.urls')),
]

paciente/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.paciente_view, name="paciente_view"),
    path("<int:paciente_id>", views.paciente_file, name="paciente_file"),
    path("new/", views.paciente_new, name="paciente_new"),
    path("api/new/", views.paciente, name="paciente"),
]

paciente/models.py
from django.db import models


import uuid
# Create your models here.
class Paciente(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    comentario = models.CharField(max_length=400, default='n/a')
    nombre = models.CharField(max_length=50, null=False, default='n/a')
    apellidos = models.CharField(max_length=100, default='n/a')
    fecha_nacimiento = models.CharField(max_length=100, default='n/a')
    tipo_documento = models.CharField(max_length=100, default='n/a')
    documento_identidad = models.CharField(max_length=100, default='n/a')
    sexo = models.CharField(max_length=100, default='n/a')
    telefono = models.CharField(max_length=100, default='n/a')
    telefono_adicional = models.CharField(max_length=100, default='n/a')
    email = models.CharField(max_length=100, default='n/a')
    
    calle = models.CharField(max_length=100, default='n/a')
    numero = models.CharField(max_length=100, default='n/a')
    puerta = models.CharField(max_length=100, default='n/a')
    pais = models.CharField(max_length=100, default='n/a')
    ciudad = models.CharField(max_length=100, default='n/a')
    cp = models.CharField(max_length=100, default='n/a')
    
    aseguradora = models.CharField(max_length=100, default='n/a')
    numero_seguro = models.CharField(max_length=100, default='n/a')
    otros_datos = models.TextField(default='n/a')
    
    fecha_registro = models.DateField(auto_now_add=True)
    photo = models.URLField(max_length=200, default="https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png")
    LPD = models.URLField(max_length=200, default='n/a')
    
    
    
class Historial(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    
    
class Episodio(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    historial = models.ForeignKey(Historial, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    diagnostico = models.TextField()
    alergias = models.TextField()
    seguimiento = models.TextField()
    recomendacion = models.TextField()
    
    
class Receta(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)
    episodio = models.ForeignKey(Episodio, on_delete=models.CASCADE)
    medicamento = models.CharField(max_length=50)
    dosis = models.CharField(max_length=50)
    frecuencia = models.CharField(max_length=50)
    duracion = models.CharField(max_length=50)
    observaciones = models.TextField()

paciente/views.py
from django.shortcuts import render

from .models import Paciente


# Create your views here.
def paciente_view(request):
    return render(request, "app/paciente/paciente_view.html")

def paciente_file(request, paciente_id):
    if request.method == "POST":
        paciente = Paciente.objects.filter(id=paciente_id).first()
    return render(request, "app/paciente/paciente_file.html", {"paciente": paciente})

def paciente_new(request):
    return render(request, "app/paciente/paciente_new.html")


def paciente(request):
    if request.method == "POST":
        paciente = Paciente()
        paciente.nombre = request.POST.get("nombre")
        paciente.apellidos = request.POST.get("apellidos")
        paciente.fecha_nacimiento = request.POST.get("fecha_nacimiento")
        paciente.tipo_documento = request.POST.get("tipo_documento")
        paciente.documento_identidad = request.POST.get("documento_identidad")
        paciente.tipo_documento = request.POST.get("tipo_documento")
        paciente.sexo = request.POST.get("sexo")
        paciente.telefono = request.POST.get("telefono")
        paciente.telefono_adicional = request.POST.get("telefono_adicional")
        paciente.email = request.POST.get("email")
        paciente.calle = request.POST.get("calle")
        paciente.numero = request.POST.get("numero")
        paciente.puerta = request.POST.get("puerta")
        paciente.pais = request.POST.get("pais")
        paciente.ciudad = request.POST.get("ciudad")
        paciente.cp = request.POST.get("cp")
        paciente.aseguradora = request.POST.get("aseguradora")
        paciente.numero_seguro = request.POST.get("numero_seguro")
        paciente.otros_datos = request.POST.get("otros_datos")
        paciente.save()
        if paciente:
            print("Paciente creado")
            return render(request, "app/paciente/paciente_file.html", {"paciente": paciente})
        else:
            print("Error al crear el paciente")
            return render(request, "app/paciente/paciente_new.html")

templates/app/paciente/paciente_file.html
{% extends 'app/base_app.html' %}
{% block title %}
    <title>Paciente</title>
{% endblock title %}


{% block content_app %}
    <h1>Ficha paciente</h1>
    <p>Nombre: {{ paciente.nombre }}</p>
{% endblock content_app %}

templates/app/paciente/paciente_new.html
{% extends 'app/base_app.html' %}
{% load static %}


{% block title %}
    <title>Nuevo Paciente</title>
{% endblock title %}

{% block libs %}
    <link rel="stylesheet" href="{% static 'css/paciente_new.css' %}">
{% endblock libs %}


{% block content_app %}
    <form class="container paciente_new" action="{%url 'app:paciente'%}" method="post">
        {% csrf_token %}
        <div class="p-2 paciente_new_header">
            <h3>Datos del Paciente</h3>
        </div>
        <!--primer bloque datos de identificacion-->
        <div class="row p-3">
            <!--User Photo-->
            <div class="col-4 d-flex flex-column align-items-center">
                <div class="row rounded-circle h-50 w-50">
                    <img src="{% static "assets/img/app/avatar_user.png" %}" alt="" class="col h-100 object-fit rounded-circle">
                </div>
                <button class="btn btn-outline-info mt-3">
                    Change Image
                </button>
            </div>

            <!--bloque de datos-->
            <div class="col">
                <h6 class="row">
                    Comentarios
                </h6>
            
                <div class="row">
                    <textarea name="comentario" id="" cols="30" rows="5" class="col form-control">

                    </textarea>
                </div>
<!-- -------------------------------------------------------- -->
                <div class="row mt-3 p-0">
                    <label for="" class="col">
                        Nombre del Paciente
                        <input name="nombre" type="text" class="row form-control">
                    </label>

                    <label for="" class="col">
                        Apellidos
                        <input name="apellidos" type="text" class="row form-control">
                    </label>
                </div>
                <!---------------------------------------------------->
                <div class="row">
                    <label for="" class="col">
                        Fecha de Nacimiento
                        <input type="date" name="fecha_nacimiento" class="row form-control">
                    </label>

                    <span for="" class="col">
                        Tipo de Documento
                        <div class="row d-flex align-items-center p-2">
                            <label for="" class="col">
                                Pasaporte
                                <input type="radio" name="tipo_documento" value="pasaporte" class="col">
                            </label>
                            <label for="" class="col">
                                DNI
                                <input type="radio" name="tipo_documento" value="dni" class="col">
                            </label>
                            <label for="" class="col">
                                Residencia
                                <input type="radio" name="tipo_documento" value="residencia" class="col">
                            </label>
                        </div>
                    </span>
                </div>
                <!---------------------------------------------------->

                <div class="row mt-3 p-0">
                    <label for="" class="col">
                        Documento de Identidad
                        <input name="documento_identidad" type="text" class="row form-control">
                    </label>

                    <label for="" class="col">
                        Sexo
                        <select name="sexo" id="" class="row form-control">
                            <option selected>n/a</option>
                            <option selected value="M">Hombre</option>
                            <option selected value="F">Mujer</option>
                        </select>
                    </label>
                </div>

            </div>
            
            <div class="row border mt-5"></div>
            <!--fin del primer bloque-------------------------------------------------------------------------------------------------------------------->

            <div class="row mt-4">

                <h5 class="col-4">
                    Datos de Contacto
                </h5>
                
                <div class="col">
                    <div class="row">
                        <label for="" class="col">
                            Telefono
                            <input type="text" name="telefono" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            E-mail
                            <input type="text" name="email" id="" class="row form-control">
                        </label>
                    </div>

                    <div class="row mt-2">
                        <label for="" class="col-6">
                            Telefono adicional
                            <input type="text" name="telefono_adicional" id="" class="row form-control">
                        </label>
                    </div>
                </div>

            </div>
            <div class="row border mt-5"></div>
            <!----------------------------------------------------------------------->
            <div class="row mt-4">

                <h5 class="col-4">
                    Direccion
                </h5>

                <div class="col">
                    <div class="row">
                        <label for="" class="col-6">
                            Calle
                            <input type="text" name="calle" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            Numero
                            <input type="text" name="numero" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            Puerta
                            <input type="text" name="puerta" id="" class="row form-control">
                        </label>
                    </div>

                    <div class="row mt-2">
                        <label for="" class="col">
                            Pais
                            <input type="text" name="pais" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            Ciudad
                            <input type="text" name="ciudad" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            Codigo Postal
                            <input type="text" name="cp" id="" class="row form-control">
                        </label>
                    </div>
                </div>

            </div>
            <!----------------------------------------------------------------------->
            <div class="row border mt-5"></div>

            <div class="row mt-4">

                <h5 class="col-4">
                    Otros datos
                </h5>

                <div class="col">
                    <div class="row">
                        <label for="" class="col-6">
                            Aseguradora
                            <input type="text" name="aseguradora" id="" class="row form-control">
                        </label>
                        <label for="" class="col">
                            Numero de Seguro Medico
                            <input type="text" name="numero_seguro" id="" class="row form-control">
                        </label>
                        
                    </div>

                    <div class="row mt-2">
                        <label for="" class="col">
                            Otros Datos
                            <textarea name="otros_datos" id="" cols="30" rows="5" class="row form-control"></textarea>
                        </label>
                    </div>
                </div>

            </div>

            <div class="row d-flex justify-content-center p-5 mt-5">
                <button type="submit" class="col-2 btn btn-info ">
                    Crear Paciente
                </button>
            </div>

            <!----------------------------------------------------------------------->
        </div>

    </form>
{% endblock content_app %}
```

templates/app/paciente/paciente_view.html
{% extends 'app/base_app.html' %}
{% block title %}
    
{% endblock title %}


{% block content_app %}
    <section class="row overflow-hidden">
        <!-- MENU crear paciente -->
        {% include 'app/paciente/components/menu_paciente_view.html' %}

        <!-- BUSCADOR -->
        {% include 'app/paciente/components/buscador_paciente_view.html' %}

        <section>
            <table class="table table-hover">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nombre</th>
                      <th scope="col">Apellidos</th>
                      <th scope="col">Telefono</th>
                      <th scope="col">Ultima Visita</th>
                      <th scope="col">Siguiente Visita</th>
                      <th scope="col">Documento de identidad</th>
                      <th scope="col">Email</th>
                      <th scope="col">Firma</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Mark</td>
                      <td>Otto</td>
                      <td>+34 666 666 666</td>
                      <td>02/01/2024</td>
                      <td>02/01/2024</td>
                      <td>12393573R</td>
                      <td>Mark@mdo.com</td>
                      <td>Firmado</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>+34 666 666 666</td>
                        <td>02/01/2024</td>
                        <td>02/01/2024</td>
                        <td>12393573R</td>
                        <td>Mark@mdo.com</td>
                        <td>Firmado</td>
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>+34 666 666 666</td>
                        <td>02/01/2024</td>
                        <td>02/01/2024</td>
                        <td>12393573R</td>
                        <td>Mark@mdo.com</td>
                        <td>Firmado</td>
                      </tr>
                  </tbody>
              </table>
        </section>
    </section>
{% endblock content_app %}
```