app/urls.py
from django.urls import path, include

from . import views

app_name = "app"

urlpatterns = [
    path("settings/", views.settings_view, name="settings_view"),
    path("paciente/", include("paciente.urls")),
]

auth_app/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('recovery/', views.recovery_view, name='recovery'),
    path('activation/', views.activation_view, name='activation'),
    
    # API
    path('api/register/', views.register, name='api_register'),
    path('api/login/', views.login, name='api_login'),
]

medical_tools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path("auth/", include('auth_app.urls')),
    path("app/", include('app.urls')),
]

templates/base_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}
        
    {% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://kit.fontawesome.com/ee37c672c1.js" crossorigin="anonymous"></script>
</head>
<body>
    <header class="container-fluid d-flex justify-content-between p-4">

        <div class="w-25 d-flex gap-2 align-items-center text-info">
            <i class="fa-solid fa-star-of-life fs-1 text-info"></i>
            <h2 class="fs-4">SM Medical</h2>
        </div>
        <nav>
            <ul class="nav d-flex gap-5 align-items-center">
                <li class="mx-3">Home</li>
                <li class="mx-3">Services</li>
                <li class="mx-3">Contact</li>
                <li class="mx-3">Test</li>
            </ul>
        </nav>

        <div class="w-25 d-flex justify-content-end">
            <a class="btn btn-outline-info" href="{% url 'auth:login' %}">
                Login
            </a>
        </div>
    </header>
    {% block home_content %}
        
    {% endblock home_content %}
    
</body>
</html>